### ISSUE TITLE
Local deploiement documentation

### ISSUE THREAD

**Issue by Erzalt** [baptisteRiviere/tileGuessr#11]
Add documentation to deploy the project locally in [wiki ](https://github.com/baptisteRiviere/tileGuessr/wiki).

**Comment by Erzalt** [comment]
Documentation added [here](https://github.com/baptisteRiviere/tileGuessr/wiki/Deploying-the-project-locally).

@baptisteRiviere You can check it and close the issue

**Comment by baptisteRiviere** [comment]
Great ! Thank you !!
