### ISSUE TITLE
Affichage des stats au dernier round

### ISSUE THREAD

**Issue by Erzalt** [baptisteRiviere/tileGuessr#6]
Il n'y a pas le résultat lors du dernier round, il est juste affiché "end of the game"

![image](https://github.com/baptisteRiviere/tileGuessr/assets/82826196/72ef0166-70d5-425a-9894-1de897e46b2b)

**Comment by baptisteRiviere** [comment]
Hello Léa, thanks for your message.

You are totally right, I have not developed these functionalities yet. You will be warned as it will be deployed!

Cheers, Baptiste

**Comment by baptisteRiviere** [comment]
Hi there, we are very excited to announce the new version of **TileGuessr** with the corrections you told us !! 
Feel free to play, the [link](https://baptisteriviere.github.io/tileGuessr) is always the same, 

best regards, the TileGuessr team
