### ISSUE TITLE
Affichage du bouton de démarrage

### ISSUE THREAD

**Issue by Emmaloup13** [baptisteRiviere/tileGuessr#7]
Bonjour,

On ne voit pas le bouton de démarrage du jeu, ça peut être contraignant, surtout si on veut jouer..
Enfin bref je l'écris car apparemment vous n'écoutez pas à l'oral !
![image](https://github.com/baptisteRiviere/tileGuessr/assets/116184717/b9df6514-4cfc-45ff-b0bf-77885ec3ce48)

**Comment by baptisteRiviere** [comment]
Hello Emma, thanks for your message !!

Infact the button exists but is hidden, I will resolve this problem soon by enabling the scrolling. The final goal would be to adapt the full content to the user page, but I am not a css pro... If you know someone with these skills which could be interested, don't hesitate to contact him !

By the way, today you can try the game by reducing the width of your navigator (by pressing F12 for example) !!
Thanks for your interest to tileGuessr, I will prevent you when all the changes I mentionned will be deployed.

Best regards, Baptiste

**Comment by baptisteRiviere** [comment]
Hi there, we are very excited to announce the new version of **TileGuessr** with the corrections you told us !! 
Feel free to play, the [link](https://baptisteriviere.github.io/tileGuessr) is always the same, 

best regards, the TileGuessr team
